<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6050QOB" ignored="4" name="Default test(failed)" tests="1" failures="1" timestamp="2022-09-20T22:50:04 IST" time="0.091" errors="0">
  <testcase name="f" time="0.021" classname="test1.NewTest1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test1.NewTest1.f(NewTest1.java:9)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="test123" time="0.0" classname="test1.NewTest1">
    <ignored/>
  </testcase> <!-- test123 -->
  <testcase name="test16" time="0.0" classname="test1.NewTest1">
    <ignored/>
  </testcase> <!-- test16 -->
  <testcase name="test12345" time="0.0" classname="test1.NewTest1">
    <ignored/>
  </testcase> <!-- test12345 -->
  <testcase name="test1234" time="0.0" classname="test1.NewTest1">
    <ignored/>
  </testcase> <!-- test1234 -->
</testsuite> <!-- Default test(failed) -->
